version: "3"

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    networks:
      - network
    environment:
      MYSQL_DATABASE: "frontend"
      # So you don't have to use root, but you can if you likes
      MYSQL_ROOT_PASSWORD: "cmpe172"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3306:3306
    volumes:
      - /tmp:/tmp
  frontend:
    image: spring-frontend
    restart: on-failure
    volumes:
      - /tmp:/tmp
    ports:
      - 8080:8080
    depends_on:
      - db 
    networks:
      - network   
    ports:
      - 8080    
    environment:
      MYSQL_HOST: "db"
    restart: always

volumes:
  schemas:
    external: false

networks:
  network:
    driver: bridge