apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: spring-back-office-api
   annotations:
     kubernetes.io/ingress.class: kong
 spec:
   rules:
   - http:
       paths:
       - path: /user
         backend:
           serviceName: spring-back-office-service
           servicePort: 80
       - path: /products
         backend:
           serviceName: spring-back-office-service
           servicePort: 80