apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: spring-apple-frontend
   annotations:
     kubernetes.io/ingress.class: kong
 spec:
   rules:
   - http:
       paths:
       - path: /
         backend:
           serviceName: spring-apple-frontend
           servicePort: 80 